export const PLATFORM_PERMISSIONS = {
  ONBOARDING: 'platform.salon_onboarding.view',
  ONBOARDING_CREATE: 'platform.salon_onboarding.create',
  ONBOARDING_UPDATE: 'platform.salon_onboarding.update',
  ONBOARDING_DELETE: 'platform.salon_onboarding.delete',
  SUBSCRIPTIONS: 'platform.subscription_plans.view',
  SUBSCRIPTION_PLANS_CREATE: 'platform.subscription_plans.create',
  SUBSCRIPTION_PLANS_UPDATE: 'platform.subscription_plans.update',
  SUBSCRIPTION_PLANS_DELETE: 'platform.subscription_plans.delete',
  BRANCHES: 'platform.branches.view',
  BRANCHES_CREATE: 'platform.branches.create',
  BRANCHES_UPDATE: 'platform.branches.update',
  AFFILIATES: 'platform.affiliates.view',
  AFFILIATES_CREATE: 'platform.affiliates.create',
  AFFILIATES_UPDATE: 'platform.affiliates.update',
  UPGRADE_REQUESTS: 'platform.upgrade_requests.view',
  UPGRADE_REQUESTS_UPDATE: 'platform.upgrade_requests.update',
  REPORTS: 'platform.reports.view',
}
