/** Tenant-scoped permission codes (mirror ApplicationPermissionSeeder). */
export const TENANT_PERMISSIONS = {
  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',
  ASSIGN_PERMISSIONS_VIEW: 'assign_permissions.view',
  ASSIGN_PERMISSIONS_UPDATE: 'assign_permissions.update',
  CATEGORIES_VIEW: 'categories.view',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  CATEGORIES_DELETE: 'categories.delete',
  SERVICES_VIEW: 'services.view',
  SERVICES_CREATE: 'services.create',
  SERVICES_UPDATE: 'services.update',
  SERVICES_DELETE: 'services.delete',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  STAFF_VIEW: 'staff.view',
  STAFF_CREATE: 'staff.create',
  STAFF_UPDATE: 'staff.update',
  STAFF_DELETE: 'staff.delete',
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_CREATE: 'branches.create',
  BRANCHES_UPDATE: 'branches.update',
  BRANCHES_DELETE: 'branches.delete',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',

  APPOINTMENTS_VIEW: 'appointments.view',
  APPOINTMENTS_CREATE: 'appointments.create',
  APPOINTMENTS_UPDATE: 'appointments.update',
  APPOINTMENTS_DELETE: 'appointments.delete',

  // Legacy route codes remain defined so removed modules fail closed.
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_MANAGE: 'customers.manage',
  CUSTOMERS_CONTACTS_VIEW: 'customers.contacts.view',
  // Billing module is gated separately; subscription UI uses settings permissions.
  BILLING_VIEW: 'settings.view',
  BILLING_MANAGE: 'settings.update',
  ANALYTICS_VIEW: 'analytics.view',
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_MANAGE: 'expenses.manage',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_MANAGE: 'inventory.manage',
  REFERRALS_VIEW: 'referrals.view',

  STAFF_EARNINGS_VIEW: 'staff.earnings.view',
  QUEUE_VIEW: 'queue.view',
  QUEUE_VIEW_ALL: 'queue.view_all',
  BOOKING_LINKS_VIEW: 'booking_links.view',
  BOOKING_LINKS_MANAGE: 'booking_links.manage',

  COMMISSIONS_VIEW: 'commissions.view',
  COMMISSIONS_MANAGE: 'commissions.manage',
  COMMISSIONS_APPROVE: 'commissions.approve',
  ANALYTICS_INSIGHTS_VIEW: 'analytics.insights.view',
  ANALYTICS_BENCHMARK_VIEW: 'analytics.benchmark.view',
  CRM_RETENTION_VIEW: 'crm.retention.view',
  CRM_RETENTION_MANAGE: 'crm.retention.manage',
  MARKETING_VIEW: 'marketing.view',
  MARKETING_MANAGE: 'marketing.manage',
  MARKETING_SEND: 'marketing.send',
  PACKAGES_VIEW: 'packages.view',
  PACKAGES_MANAGE: 'packages.manage',
  PACKAGES_SELL: 'packages.sell',
  PACKAGES_REDEEM: 'packages.redeem',
  GIFTCARDS_VIEW: 'giftcards.view',
  GIFTCARDS_MANAGE: 'giftcards.manage',
  GIFTCARDS_SELL: 'giftcards.sell',
  GIFTCARDS_REDEEM: 'giftcards.redeem',
  GIFTCARDS_ADJUST: 'giftcards.adjust',
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_MANAGE: 'payroll.manage',
  PAYROLL_APPROVE: 'payroll.approve',
  PAYMENTS_POLICY_MANAGE: 'payments.policy.manage',
  PAYMENTS_CHARGE: 'payments.charge',
  PAYMENTS_REFUND: 'payments.refund',
  PAYMENTS_WAIVE: 'payments.waive',
  WAITLIST_VIEW: 'waitlist.view',
  WAITLIST_MANAGE: 'waitlist.manage',
  REVIEWS_VIEW: 'reviews.view',
  REVIEWS_MANAGE: 'reviews.manage',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_PUNCH: 'attendance.punch',
  LEAVE_APPROVE: 'leave.approve',
  PRICING_RULES_VIEW: 'pricing_rules.view',
  PRICING_RULES_MANAGE: 'pricing_rules.manage',
}

export function isPlatformPermissionCode(code) {
  return typeof code === 'string' && code.startsWith('platform.')
}
